# Generated by Django 4.0.7 on 2022-10-30 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('userId', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=38)),
            ],
        ),
        migrations.CreateModel(
            name='expenseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseCategory', models.CharField(default=True, max_length=38)),
                ('date', models.DateTimeField(default=0)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('comments', models.TextField(default=None, max_length=38)),
                ('recieptImage', models.ImageField(blank=True, default=1, upload_to='')),
                ('approvedStatus', models.TextField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejecteed')], default='Pending')),
                ('userDetail', models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='expense_api.userdetails')),
            ],
        ),
    ]
