# Generated by Django 4.0.7 on 2022-10-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedetails',
            name='approvedComments',
            field=models.TextField(blank=True, default=None, max_length=38),
        ),
    ]
