# Generated by Django 4.0.7 on 2022-10-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_api', '0002_expensedetails_approvedcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='approvedComments',
            field=models.TextField(blank=True, default=1, max_length=38),
        ),
    ]
