# Generated by Django 4.0.7 on 2022-10-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_api', '0004_alter_expensedetails_approvedcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensedetails',
            old_name='approvedComments',
            new_name='approversComments',
        ),
    ]
