# Generated by Django 4.0.7 on 2022-10-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_api', '0005_rename_approvedcomments_expensedetails_approverscomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='approversComments',
            field=models.TextField(blank=True, default='Pending', max_length=38),
        ),
    ]
